apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-mysql-deployment
  namespace: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-mysql
  template:
    metadata:
      labels:
        app: springboot-mysql
    spec:
      nodeSelector:
        kubernetes.io/hostname: compute.3s.com
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: achatdb
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      - name: springboot-container
        image: achrefdoce/chat:latest
        ports:
        - containerPort: 8089
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://localhost:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: SPRING_DATASOURCE_INITIALIZATION_MODE
          value: always
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-mysql
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30000
  type: NodePort
