version: '3.8'
services:
  backend:
    image: malekkkk/achat:1.0
    restart: unless-stopped
    ports:
      - "8089:8089" 
    depends_on:
      - db
  db:
    image: mysql:5.7 
    restart: unless-stopped
    ports:
      - "3307:3306" 
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - dataDb:/var/lib/mysql 

volumes:
  dataDb: