version: "2"
services:
  frontend:
    image: nourchenebouarada/angular:latest
    restart: unless-stopped
    ports:
      - "8082:80" 
  mysql:
    image: mysql:8
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - my_network
  backend:
    depends_on: [mysql]
    image:  nourchenebouarada/springimage1:latest
    restart: unless-stopped
    ports:
      - "8089:8089"  # Port du backend
    networks:
      - my_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root  
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
networks:
  my_network:
    driver: bridge


