version: "2"
services:
  front:
    depends_on: [spring]
    image: achrefdoce/achref2:latest
    container_name: front
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - my_network

      
  spring:
    depends_on: [mysql]
    image: achrefdoce/achat:1-0
    container_name: spring

    restart: unless-stopped
    ports:
      - "8089:8089"  
    networks:
      - my_network
  
      
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3037:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
