version: "2"
services:
  front:
    depends_on: [spring]
    image:  achrefdoce/achreffront:latest
    restart: unless-stopped
    ports:
      - "80:80"
  spring:
    depends_on: [mysql]
    image: achrefdoce/achat:1-0
    restart: unless-stopped
    ports:
      - "8089:8089"
  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

