version: "3.8"
networks:
  mynetwork: # Créez un réseau personnalisé ici

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Définissez le volume "db_data" ici
    networks:
      - mynetwork  # Attachez le service au réseau personnalisé
  backend:
    image: youssefhadiji956/achat:1-0 
    restart: unless-stopped
    ports:
      - 8089:8089
    depends_on:
      - db
    networks:
      - mynetwork
      
volumes:
  db_data:
