version: "2"
services: 
  front:
    image: youssefhadiji956/front:3-0  # Replace with the actual image for your front-end
    restart: unless-stopped
    ports:
      - 80:80
  backend:
    depends_on: [db]
    image: youssefhadiji956/achat:6-0
    restart: unless-stopped
    ports:
      - "8089:8089"

  db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql-db
    ports:
      - "3307:3306"  # Fix the indentation here
